### ISSUE TITLE
Other Badges

### ISSUE THREAD

**Issue by Ekstropiya** [Ekstropiya/Spotify-Shield#6]
Spotify-Shield doesn't have to be limited to just playback status, some other badges could be:

- Click to follow your profile/profile badge.

![](https://img.shields.io/badge/Extropy-1%20follower-1DB954?labelColor=117032&logo=spotify)

- Playlist badge.

![](https://img.shields.io/badge/Your%20Top%20Songs%202021-100%20songs,%206%20hr%2059%20min-1DB954?labelColor=117032&logo=spotify)

- Podcast badge (would be good for organizations that have podcasts, or anyone else that does)

![](https://img.shields.io/badge/Smart%20Talks%20with%20IBM-13%20episodes-1DB954?labelColor=117032&logo=spotify)
*I couldn't manually encode the podcast thumbnail and get it to work, but that would be cool.*

- Artist badge/Top artist this month:

![](https://img.shields.io/badge/-Talking%20Heads-1DB954?labelColor=117032&logo=spotify)
*I also couldn't manually encode an image for this to work, but spotify artists do seem to have a sort of thumbnail/picture.*

**Comment by Ekstropiya** [comment]
Most of these are pretty useless, but wouldn't hurt to see if anyone likes them.

**Comment by Styro457** [comment]
You should add a song one too

**Comment by Ekstropiya** [comment]
Good idea
